In [4]:
import pandas as pd

df = pd.read_csv("../../data/HU_IRB_AOD500_preprocessed.csv", parse_dates=["datetime"])

print("Null values:\n", df.isnull().sum())
print("\nShape:", df.shape)
display(df.head())

# 1-hour average
df_hourly = df.set_index("datetime").resample("1h").mean().reset_index()

print("-----------"*80)

print("Null values:\n", df.isnull().sum())
print("Shape:", df_hourly.shape)
display(df_hourly.head())

Null values:
 datetime     0
AOD_500nm    0
dtype: int64

Shape: (27972, 2)

             datetime  AOD_500nm
0 2021-03-01 18:56:43   0.163369
1 2021-03-01 19:01:43   0.144799
2 2021-03-01 20:16:42   0.170261
3 2021-03-01 20:21:42   0.179449
4 2021-03-01 20:30:52   0.152524

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Null values:
 datetime     0
AOD_500nm    0
dtype: int64
Shape: (33099, 2)

             datetime  AOD_500nm
0 2021-03-01 18:00:00   0.163369
1 2021-03-01 19:00:00   0.144799
2 2021-03-01 20:00:00   0.167149
3 2021-03-01 21:00:00   0.189530
4 2021-03-01 22:00:00   0.184450